// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFb2Ljq2M-kikPJgiNvgbhg00a1G3NxYo',
    appId: '1:640967073661:web:0b71aff3dc6047a8f2f614',
    messagingSenderId: '640967073661',
    projectId: 'roomie-v2',
    authDomain: 'roomie-v2.firebaseapp.com',
    databaseURL: 'https://roomie-v2-default-rtdb.firebaseio.com',
    storageBucket: 'roomie-v2.appspot.com',
    measurementId: 'G-JBWHR21R37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIN0eRLSzmOnDGXJ-hwn3kYebJm4abXA',
    appId: '1:640967073661:android:0b8732de044fb098f2f614',
    messagingSenderId: '640967073661',
    projectId: 'roomie-v2',
    databaseURL: 'https://roomie-v2-default-rtdb.firebaseio.com',
    storageBucket: 'roomie-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmA5p-td-y-3jC9vsX43TDZoERTY8CPXs',
    appId: '1:640967073661:ios:5d2d0cb47d11d460f2f614',
    messagingSenderId: '640967073661',
    projectId: 'roomie-v2',
    databaseURL: 'https://roomie-v2-default-rtdb.firebaseio.com',
    storageBucket: 'roomie-v2.appspot.com',
    iosClientId: '640967073661-4bpfu7qtsn03keqhe1hdpluqcubjm0ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomieV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmA5p-td-y-3jC9vsX43TDZoERTY8CPXs',
    appId: '1:640967073661:ios:5d2d0cb47d11d460f2f614',
    messagingSenderId: '640967073661',
    projectId: 'roomie-v2',
    databaseURL: 'https://roomie-v2-default-rtdb.firebaseio.com',
    storageBucket: 'roomie-v2.appspot.com',
    iosClientId: '640967073661-4bpfu7qtsn03keqhe1hdpluqcubjm0ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomieV2',
  );
}
